### ISSUE TITLE
Evolution with LinearOperators not working

### ISSUE THREAD

**Issue by adamcallison** [jcmgray/quimb#43] opened 2019-12-14 20:33 UTC
I'm not sure what is happening but evolution by integration with custom linear operators is producing the wrong evolution. (Even if you simply wrap a matrix Hamiltonian as a LinearOperator). I realised this only when trying to extend the tests for something else. I will try to figure it out.

**Comment by jcmgray** [comment] 2019-12-16 13:00
Interesting, do you have a short reproducer of the problem?

**Comment by jcmgray** [comment] 2019-12-16 13:20
I've added [LinearOperators to one of the tests](https://github.com/jcmgray/quimb/commit/d613b9659129d716bb4cd42898b747c326582541) that at least seems to be working.

**Comment by jcmgray** [comment] 2019-12-16 14:44
(Hopefully) resolved by #44.

**Closed by jcmgray** 2019-12-16 14:44 UTC
